// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/project-management.proto

package projectManagement

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MilestoneModel struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Done                 bool     `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MilestoneModel) Reset()         { *m = MilestoneModel{} }
func (m *MilestoneModel) String() string { return proto.CompactTextString(m) }
func (*MilestoneModel) ProtoMessage()    {}
func (*MilestoneModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{0}
}

func (m *MilestoneModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MilestoneModel.Unmarshal(m, b)
}
func (m *MilestoneModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MilestoneModel.Marshal(b, m, deterministic)
}
func (m *MilestoneModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MilestoneModel.Merge(m, src)
}
func (m *MilestoneModel) XXX_Size() int {
	return xxx_messageInfo_MilestoneModel.Size(m)
}
func (m *MilestoneModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MilestoneModel.DiscardUnknown(m)
}

var xxx_messageInfo_MilestoneModel proto.InternalMessageInfo

func (m *MilestoneModel) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *MilestoneModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MilestoneModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MilestoneModel) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MilestoneModel) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *MilestoneModel) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type AddMilestoneRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMilestoneRequest) Reset()         { *m = AddMilestoneRequest{} }
func (m *AddMilestoneRequest) String() string { return proto.CompactTextString(m) }
func (*AddMilestoneRequest) ProtoMessage()    {}
func (*AddMilestoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{1}
}

func (m *AddMilestoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMilestoneRequest.Unmarshal(m, b)
}
func (m *AddMilestoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMilestoneRequest.Marshal(b, m, deterministic)
}
func (m *AddMilestoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMilestoneRequest.Merge(m, src)
}
func (m *AddMilestoneRequest) XXX_Size() int {
	return xxx_messageInfo_AddMilestoneRequest.Size(m)
}
func (m *AddMilestoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMilestoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMilestoneRequest proto.InternalMessageInfo

func (m *AddMilestoneRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *AddMilestoneRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddMilestoneRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddMilestoneRequest) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AddMilestoneRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type AddMilestoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMilestoneResponse) Reset()         { *m = AddMilestoneResponse{} }
func (m *AddMilestoneResponse) String() string { return proto.CompactTextString(m) }
func (*AddMilestoneResponse) ProtoMessage()    {}
func (*AddMilestoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{2}
}

func (m *AddMilestoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMilestoneResponse.Unmarshal(m, b)
}
func (m *AddMilestoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMilestoneResponse.Marshal(b, m, deterministic)
}
func (m *AddMilestoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMilestoneResponse.Merge(m, src)
}
func (m *AddMilestoneResponse) XXX_Size() int {
	return xxx_messageInfo_AddMilestoneResponse.Size(m)
}
func (m *AddMilestoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMilestoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMilestoneResponse proto.InternalMessageInfo

func (m *AddMilestoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditMilestoneRequest struct {
	Milestoneid          string   `protobuf:"bytes,1,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	Projectid            string   `protobuf:"bytes,2,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Users                []string `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	Weight               int32    `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMilestoneRequest) Reset()         { *m = EditMilestoneRequest{} }
func (m *EditMilestoneRequest) String() string { return proto.CompactTextString(m) }
func (*EditMilestoneRequest) ProtoMessage()    {}
func (*EditMilestoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{3}
}

func (m *EditMilestoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMilestoneRequest.Unmarshal(m, b)
}
func (m *EditMilestoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMilestoneRequest.Marshal(b, m, deterministic)
}
func (m *EditMilestoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMilestoneRequest.Merge(m, src)
}
func (m *EditMilestoneRequest) XXX_Size() int {
	return xxx_messageInfo_EditMilestoneRequest.Size(m)
}
func (m *EditMilestoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMilestoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditMilestoneRequest proto.InternalMessageInfo

func (m *EditMilestoneRequest) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

func (m *EditMilestoneRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *EditMilestoneRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditMilestoneRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditMilestoneRequest) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *EditMilestoneRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type EditMilestoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMilestoneResponse) Reset()         { *m = EditMilestoneResponse{} }
func (m *EditMilestoneResponse) String() string { return proto.CompactTextString(m) }
func (*EditMilestoneResponse) ProtoMessage()    {}
func (*EditMilestoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{4}
}

func (m *EditMilestoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMilestoneResponse.Unmarshal(m, b)
}
func (m *EditMilestoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMilestoneResponse.Marshal(b, m, deterministic)
}
func (m *EditMilestoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMilestoneResponse.Merge(m, src)
}
func (m *EditMilestoneResponse) XXX_Size() int {
	return xxx_messageInfo_EditMilestoneResponse.Size(m)
}
func (m *EditMilestoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMilestoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditMilestoneResponse proto.InternalMessageInfo

func (m *EditMilestoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteMilestoneRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Milestoneid          string   `protobuf:"bytes,2,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMilestoneRequest) Reset()         { *m = DeleteMilestoneRequest{} }
func (m *DeleteMilestoneRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMilestoneRequest) ProtoMessage()    {}
func (*DeleteMilestoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{5}
}

func (m *DeleteMilestoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMilestoneRequest.Unmarshal(m, b)
}
func (m *DeleteMilestoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMilestoneRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMilestoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMilestoneRequest.Merge(m, src)
}
func (m *DeleteMilestoneRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMilestoneRequest.Size(m)
}
func (m *DeleteMilestoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMilestoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMilestoneRequest proto.InternalMessageInfo

func (m *DeleteMilestoneRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *DeleteMilestoneRequest) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

type DeleteMilestoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMilestoneResponse) Reset()         { *m = DeleteMilestoneResponse{} }
func (m *DeleteMilestoneResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMilestoneResponse) ProtoMessage()    {}
func (*DeleteMilestoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{6}
}

func (m *DeleteMilestoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMilestoneResponse.Unmarshal(m, b)
}
func (m *DeleteMilestoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMilestoneResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMilestoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMilestoneResponse.Merge(m, src)
}
func (m *DeleteMilestoneResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMilestoneResponse.Size(m)
}
func (m *DeleteMilestoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMilestoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMilestoneResponse proto.InternalMessageInfo

func (m *DeleteMilestoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MilestoneCompletionRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Milestoneid          string   `protobuf:"bytes,2,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MilestoneCompletionRequest) Reset()         { *m = MilestoneCompletionRequest{} }
func (m *MilestoneCompletionRequest) String() string { return proto.CompactTextString(m) }
func (*MilestoneCompletionRequest) ProtoMessage()    {}
func (*MilestoneCompletionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{7}
}

func (m *MilestoneCompletionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MilestoneCompletionRequest.Unmarshal(m, b)
}
func (m *MilestoneCompletionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MilestoneCompletionRequest.Marshal(b, m, deterministic)
}
func (m *MilestoneCompletionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MilestoneCompletionRequest.Merge(m, src)
}
func (m *MilestoneCompletionRequest) XXX_Size() int {
	return xxx_messageInfo_MilestoneCompletionRequest.Size(m)
}
func (m *MilestoneCompletionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MilestoneCompletionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MilestoneCompletionRequest proto.InternalMessageInfo

func (m *MilestoneCompletionRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *MilestoneCompletionRequest) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

type MilestoneCompletionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MilestoneCompletionResponse) Reset()         { *m = MilestoneCompletionResponse{} }
func (m *MilestoneCompletionResponse) String() string { return proto.CompactTextString(m) }
func (*MilestoneCompletionResponse) ProtoMessage()    {}
func (*MilestoneCompletionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{8}
}

func (m *MilestoneCompletionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MilestoneCompletionResponse.Unmarshal(m, b)
}
func (m *MilestoneCompletionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MilestoneCompletionResponse.Marshal(b, m, deterministic)
}
func (m *MilestoneCompletionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MilestoneCompletionResponse.Merge(m, src)
}
func (m *MilestoneCompletionResponse) XXX_Size() int {
	return xxx_messageInfo_MilestoneCompletionResponse.Size(m)
}
func (m *MilestoneCompletionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MilestoneCompletionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MilestoneCompletionResponse proto.InternalMessageInfo

func (m *MilestoneCompletionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetProjectMembersRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	CurrentMembers       []string `protobuf:"bytes,2,rep,name=currentMembers,proto3" json:"currentMembers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectMembersRequest) Reset()         { *m = GetProjectMembersRequest{} }
func (m *GetProjectMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectMembersRequest) ProtoMessage()    {}
func (*GetProjectMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{9}
}

func (m *GetProjectMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectMembersRequest.Unmarshal(m, b)
}
func (m *GetProjectMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectMembersRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectMembersRequest.Merge(m, src)
}
func (m *GetProjectMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectMembersRequest.Size(m)
}
func (m *GetProjectMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectMembersRequest proto.InternalMessageInfo

func (m *GetProjectMembersRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *GetProjectMembersRequest) GetCurrentMembers() []string {
	if m != nil {
		return m.CurrentMembers
	}
	return nil
}

type GetProjectMembersResponse struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Users                []*UserTuple `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetProjectMembersResponse) Reset()         { *m = GetProjectMembersResponse{} }
func (m *GetProjectMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectMembersResponse) ProtoMessage()    {}
func (*GetProjectMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{10}
}

func (m *GetProjectMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectMembersResponse.Unmarshal(m, b)
}
func (m *GetProjectMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectMembersResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectMembersResponse.Merge(m, src)
}
func (m *GetProjectMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectMembersResponse.Size(m)
}
func (m *GetProjectMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectMembersResponse proto.InternalMessageInfo

func (m *GetProjectMembersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetProjectMembersResponse) GetUsers() []*UserTuple {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserTuple struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTuple) Reset()         { *m = UserTuple{} }
func (m *UserTuple) String() string { return proto.CompactTextString(m) }
func (*UserTuple) ProtoMessage()    {}
func (*UserTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{11}
}

func (m *UserTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTuple.Unmarshal(m, b)
}
func (m *UserTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTuple.Marshal(b, m, deterministic)
}
func (m *UserTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTuple.Merge(m, src)
}
func (m *UserTuple) XXX_Size() int {
	return xxx_messageInfo_UserTuple.Size(m)
}
func (m *UserTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTuple.DiscardUnknown(m)
}

var xxx_messageInfo_UserTuple proto.InternalMessageInfo

func (m *UserTuple) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserTuple) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type InviteUserRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	ReceipientEmail      string   `protobuf:"bytes,2,opt,name=receipientEmail,proto3" json:"receipientEmail,omitempty"`
	SenderEmail          string   `protobuf:"bytes,3,opt,name=senderEmail,proto3" json:"senderEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserRequest) Reset()         { *m = InviteUserRequest{} }
func (m *InviteUserRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUserRequest) ProtoMessage()    {}
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{12}
}

func (m *InviteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserRequest.Unmarshal(m, b)
}
func (m *InviteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserRequest.Marshal(b, m, deterministic)
}
func (m *InviteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserRequest.Merge(m, src)
}
func (m *InviteUserRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUserRequest.Size(m)
}
func (m *InviteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserRequest proto.InternalMessageInfo

func (m *InviteUserRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *InviteUserRequest) GetReceipientEmail() string {
	if m != nil {
		return m.ReceipientEmail
	}
	return ""
}

func (m *InviteUserRequest) GetSenderEmail() string {
	if m != nil {
		return m.SenderEmail
	}
	return ""
}

type InviteUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserResponse) Reset()         { *m = InviteUserResponse{} }
func (m *InviteUserResponse) String() string { return proto.CompactTextString(m) }
func (*InviteUserResponse) ProtoMessage()    {}
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{13}
}

func (m *InviteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserResponse.Unmarshal(m, b)
}
func (m *InviteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserResponse.Marshal(b, m, deterministic)
}
func (m *InviteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserResponse.Merge(m, src)
}
func (m *InviteUserResponse) XXX_Size() int {
	return xxx_messageInfo_InviteUserResponse.Size(m)
}
func (m *InviteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserResponse proto.InternalMessageInfo

func (m *InviteUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddUserRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Useremail            string   `protobuf:"bytes,2,opt,name=useremail,proto3" json:"useremail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{14}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *AddUserRequest) GetUseremail() string {
	if m != nil {
		return m.Useremail
	}
	return ""
}

type AddUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{15}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveUserRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Useremail            string   `protobuf:"bytes,2,opt,name=useremail,proto3" json:"useremail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserRequest) Reset()         { *m = RemoveUserRequest{} }
func (m *RemoveUserRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveUserRequest) ProtoMessage()    {}
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{16}
}

func (m *RemoveUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserRequest.Unmarshal(m, b)
}
func (m *RemoveUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserRequest.Marshal(b, m, deterministic)
}
func (m *RemoveUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserRequest.Merge(m, src)
}
func (m *RemoveUserRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveUserRequest.Size(m)
}
func (m *RemoveUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserRequest proto.InternalMessageInfo

func (m *RemoveUserRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *RemoveUserRequest) GetUseremail() string {
	if m != nil {
		return m.Useremail
	}
	return ""
}

type RemoveUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserResponse) Reset()         { *m = RemoveUserResponse{} }
func (m *RemoveUserResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveUserResponse) ProtoMessage()    {}
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{17}
}

func (m *RemoveUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserResponse.Unmarshal(m, b)
}
func (m *RemoveUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserResponse.Marshal(b, m, deterministic)
}
func (m *RemoveUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserResponse.Merge(m, src)
}
func (m *RemoveUserResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveUserResponse.Size(m)
}
func (m *RemoveUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserResponse proto.InternalMessageInfo

func (m *RemoveUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RejectUserRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Useremail            string   `protobuf:"bytes,2,opt,name=useremail,proto3" json:"useremail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectUserRequest) Reset()         { *m = RejectUserRequest{} }
func (m *RejectUserRequest) String() string { return proto.CompactTextString(m) }
func (*RejectUserRequest) ProtoMessage()    {}
func (*RejectUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{18}
}

func (m *RejectUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectUserRequest.Unmarshal(m, b)
}
func (m *RejectUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectUserRequest.Marshal(b, m, deterministic)
}
func (m *RejectUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectUserRequest.Merge(m, src)
}
func (m *RejectUserRequest) XXX_Size() int {
	return xxx_messageInfo_RejectUserRequest.Size(m)
}
func (m *RejectUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectUserRequest proto.InternalMessageInfo

func (m *RejectUserRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *RejectUserRequest) GetUseremail() string {
	if m != nil {
		return m.Useremail
	}
	return ""
}

type RejectUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectUserResponse) Reset()         { *m = RejectUserResponse{} }
func (m *RejectUserResponse) String() string { return proto.CompactTextString(m) }
func (*RejectUserResponse) ProtoMessage()    {}
func (*RejectUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{19}
}

func (m *RejectUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectUserResponse.Unmarshal(m, b)
}
func (m *RejectUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectUserResponse.Marshal(b, m, deterministic)
}
func (m *RejectUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectUserResponse.Merge(m, src)
}
func (m *RejectUserResponse) XXX_Size() int {
	return xxx_messageInfo_RejectUserResponse.Size(m)
}
func (m *RejectUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectUserResponse proto.InternalMessageInfo

func (m *RejectUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type TransferLeaderRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	NewLeader            string   `protobuf:"bytes,2,opt,name=new_leader,json=newLeader,proto3" json:"new_leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferLeaderRequest) Reset()         { *m = TransferLeaderRequest{} }
func (m *TransferLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*TransferLeaderRequest) ProtoMessage()    {}
func (*TransferLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{20}
}

func (m *TransferLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferLeaderRequest.Unmarshal(m, b)
}
func (m *TransferLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferLeaderRequest.Marshal(b, m, deterministic)
}
func (m *TransferLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferLeaderRequest.Merge(m, src)
}
func (m *TransferLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_TransferLeaderRequest.Size(m)
}
func (m *TransferLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferLeaderRequest proto.InternalMessageInfo

func (m *TransferLeaderRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *TransferLeaderRequest) GetNewLeader() string {
	if m != nil {
		return m.NewLeader
	}
	return ""
}

type TransferLeaderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferLeaderResponse) Reset()         { *m = TransferLeaderResponse{} }
func (m *TransferLeaderResponse) String() string { return proto.CompactTextString(m) }
func (*TransferLeaderResponse) ProtoMessage()    {}
func (*TransferLeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{21}
}

func (m *TransferLeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferLeaderResponse.Unmarshal(m, b)
}
func (m *TransferLeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferLeaderResponse.Marshal(b, m, deterministic)
}
func (m *TransferLeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferLeaderResponse.Merge(m, src)
}
func (m *TransferLeaderResponse) XXX_Size() int {
	return xxx_messageInfo_TransferLeaderResponse.Size(m)
}
func (m *TransferLeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferLeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferLeaderResponse proto.InternalMessageInfo

func (m *TransferLeaderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AnnouncementRequest struct {
	Projectid            string   `protobuf:"bytes,1,opt,name=projectid,proto3" json:"projectid,omitempty"`
	Announcementid       string   `protobuf:"bytes,2,opt,name=announcementid,proto3" json:"announcementid,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementRequest) Reset()         { *m = AnnouncementRequest{} }
func (m *AnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*AnnouncementRequest) ProtoMessage()    {}
func (*AnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{22}
}

func (m *AnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementRequest.Unmarshal(m, b)
}
func (m *AnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementRequest.Marshal(b, m, deterministic)
}
func (m *AnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementRequest.Merge(m, src)
}
func (m *AnnouncementRequest) XXX_Size() int {
	return xxx_messageInfo_AnnouncementRequest.Size(m)
}
func (m *AnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementRequest proto.InternalMessageInfo

func (m *AnnouncementRequest) GetProjectid() string {
	if m != nil {
		return m.Projectid
	}
	return ""
}

func (m *AnnouncementRequest) GetAnnouncementid() string {
	if m != nil {
		return m.Announcementid
	}
	return ""
}

func (m *AnnouncementRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AnnouncementRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AnnouncementResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementResponse) Reset()         { *m = AnnouncementResponse{} }
func (m *AnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*AnnouncementResponse) ProtoMessage()    {}
func (*AnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73530e506fe37ed3, []int{23}
}

func (m *AnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementResponse.Unmarshal(m, b)
}
func (m *AnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementResponse.Marshal(b, m, deterministic)
}
func (m *AnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementResponse.Merge(m, src)
}
func (m *AnnouncementResponse) XXX_Size() int {
	return xxx_messageInfo_AnnouncementResponse.Size(m)
}
func (m *AnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementResponse proto.InternalMessageInfo

func (m *AnnouncementResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MilestoneModel)(nil), "projectManagement.MilestoneModel")
	proto.RegisterType((*AddMilestoneRequest)(nil), "projectManagement.AddMilestoneRequest")
	proto.RegisterType((*AddMilestoneResponse)(nil), "projectManagement.AddMilestoneResponse")
	proto.RegisterType((*EditMilestoneRequest)(nil), "projectManagement.EditMilestoneRequest")
	proto.RegisterType((*EditMilestoneResponse)(nil), "projectManagement.EditMilestoneResponse")
	proto.RegisterType((*DeleteMilestoneRequest)(nil), "projectManagement.DeleteMilestoneRequest")
	proto.RegisterType((*DeleteMilestoneResponse)(nil), "projectManagement.DeleteMilestoneResponse")
	proto.RegisterType((*MilestoneCompletionRequest)(nil), "projectManagement.MilestoneCompletionRequest")
	proto.RegisterType((*MilestoneCompletionResponse)(nil), "projectManagement.MilestoneCompletionResponse")
	proto.RegisterType((*GetProjectMembersRequest)(nil), "projectManagement.GetProjectMembersRequest")
	proto.RegisterType((*GetProjectMembersResponse)(nil), "projectManagement.GetProjectMembersResponse")
	proto.RegisterType((*UserTuple)(nil), "projectManagement.UserTuple")
	proto.RegisterType((*InviteUserRequest)(nil), "projectManagement.InviteUserRequest")
	proto.RegisterType((*InviteUserResponse)(nil), "projectManagement.InviteUserResponse")
	proto.RegisterType((*AddUserRequest)(nil), "projectManagement.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "projectManagement.AddUserResponse")
	proto.RegisterType((*RemoveUserRequest)(nil), "projectManagement.RemoveUserRequest")
	proto.RegisterType((*RemoveUserResponse)(nil), "projectManagement.RemoveUserResponse")
	proto.RegisterType((*RejectUserRequest)(nil), "projectManagement.RejectUserRequest")
	proto.RegisterType((*RejectUserResponse)(nil), "projectManagement.RejectUserResponse")
	proto.RegisterType((*TransferLeaderRequest)(nil), "projectManagement.TransferLeaderRequest")
	proto.RegisterType((*TransferLeaderResponse)(nil), "projectManagement.TransferLeaderResponse")
	proto.RegisterType((*AnnouncementRequest)(nil), "projectManagement.AnnouncementRequest")
	proto.RegisterType((*AnnouncementResponse)(nil), "projectManagement.AnnouncementResponse")
}

func init() { proto.RegisterFile("protos/project-management.proto", fileDescriptor_73530e506fe37ed3) }

var fileDescriptor_73530e506fe37ed3 = []byte{
	// 942 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xd6, 0xac, 0x7f, 0x62, 0x97, 0xf1, 0xda, 0x6e, 0xaf, 0x9d, 0xf1, 0xc4, 0x51, 0x96, 0x16,
	0x84, 0x4d, 0x42, 0x76, 0xc0, 0x39, 0x20, 0x71, 0x41, 0x16, 0x44, 0x28, 0x52, 0x0c, 0xd6, 0xca,
	0x48, 0x1c, 0x90, 0x60, 0xb2, 0x53, 0x59, 0x1a, 0xcd, 0xf4, 0x6c, 0xa6, 0x7b, 0x63, 0x38, 0xe4,
	0x00, 0x12, 0x47, 0x4e, 0x11, 0x07, 0x24, 0x1e, 0x85, 0xb7, 0xe0, 0x15, 0x78, 0x0f, 0x50, 0xf7,
	0xf4, 0xce, 0xce, 0x4f, 0xaf, 0x67, 0x40, 0x16, 0xb7, 0xed, 0xaa, 0xea, 0xfa, 0xbe, 0xea, 0xae,
	0xfe, 0x6a, 0x16, 0xee, 0x4c, 0xd3, 0x44, 0x26, 0xc2, 0x9f, 0xa6, 0xc9, 0x77, 0x38, 0x96, 0x0f,
	0xe3, 0x80, 0x07, 0x13, 0x8c, 0x91, 0xcb, 0xa1, 0xf6, 0x90, 0x3d, 0xe3, 0x39, 0xcb, 0x1d, 0xde,
	0xf1, 0x24, 0x49, 0x26, 0x11, 0xfa, 0xc1, 0x94, 0xf9, 0x01, 0xe7, 0x89, 0x0c, 0x24, 0x4b, 0xb8,
	0xc8, 0x36, 0xd0, 0xdf, 0x1d, 0xe8, 0x9e, 0xb1, 0x08, 0x85, 0x4c, 0x38, 0x9e, 0x25, 0x21, 0x46,
	0x64, 0x17, 0x56, 0xbe, 0x67, 0xa1, 0xeb, 0xf4, 0x9d, 0xc1, 0xe6, 0x48, 0xfd, 0x24, 0x3d, 0x58,
	0x93, 0x4c, 0x46, 0xe8, 0x76, 0xb4, 0x2d, 0x5b, 0x90, 0x3e, 0x6c, 0x85, 0x28, 0xc6, 0x29, 0x9b,
	0xaa, 0x84, 0xee, 0x8a, 0xf6, 0x15, 0x4d, 0x6a, 0xdf, 0x4c, 0x60, 0x2a, 0xdc, 0xd5, 0xfe, 0x8a,
	0xda, 0xa7, 0x17, 0xe4, 0x10, 0xd6, 0x2f, 0x91, 0x4d, 0xbe, 0x95, 0xee, 0x5a, 0xdf, 0x19, 0xac,
	0x8d, 0xcc, 0x8a, 0x10, 0x58, 0x0d, 0x13, 0x8e, 0xee, 0x7a, 0xdf, 0x19, 0x6c, 0x8c, 0xf4, 0x6f,
	0xfa, 0x9b, 0x03, 0xfb, 0xa7, 0x61, 0x98, 0x33, 0x1c, 0xe1, 0x8b, 0x19, 0x0a, 0x49, 0x8e, 0x61,
	0xd3, 0x54, 0x9a, 0x33, 0x5d, 0x18, 0xfe, 0x1f, 0xbe, 0xf4, 0x3d, 0xe8, 0x95, 0xa9, 0x89, 0x69,
	0xc2, 0x05, 0x12, 0x17, 0x6e, 0x88, 0xd9, 0x78, 0x8c, 0x42, 0x68, 0x66, 0x1b, 0xa3, 0xf9, 0x92,
	0xfe, 0xe1, 0x40, 0xef, 0x71, 0xc8, 0x64, 0xad, 0x9c, 0x3e, 0x6c, 0xc5, 0x73, 0x5b, 0x5e, 0x50,
	0xd1, 0x54, 0x2e, 0xb8, 0xb3, 0xb4, 0xe0, 0x95, 0x2b, 0x0a, 0x5e, 0xbd, 0xa2, 0xe0, 0x35, 0x7b,
	0xc1, 0xeb, 0xa5, 0x82, 0xdf, 0x87, 0x83, 0x0a, 0xfb, 0xc6, 0x8a, 0xbf, 0x84, 0xc3, 0x4f, 0x30,
	0x42, 0x89, 0xff, 0xf2, 0x06, 0x2b, 0x07, 0xd2, 0xa9, 0x1d, 0x08, 0x7d, 0x04, 0x37, 0x6b, 0x99,
	0x1b, 0xe9, 0x7c, 0x05, 0x5e, 0x1e, 0xfe, 0x71, 0x12, 0x4f, 0x23, 0x54, 0xc7, 0x70, 0x5d, 0x94,
	0x3e, 0x80, 0x5b, 0xd6, 0xec, 0x8d, 0xb4, 0xbe, 0x01, 0xf7, 0x53, 0x94, 0xe7, 0xe6, 0xe9, 0x62,
	0xfc, 0x0c, 0x53, 0xd1, 0x8e, 0xd4, 0x5d, 0xe8, 0x8e, 0x67, 0x69, 0x8a, 0x7c, 0xbe, 0xcd, 0xed,
	0xe8, 0x9b, 0xac, 0x58, 0x29, 0x83, 0x23, 0x0b, 0x42, 0x13, 0x31, 0x72, 0x32, 0xef, 0x0f, 0x95,
	0x75, 0xeb, 0xe4, 0x78, 0x58, 0x93, 0x97, 0xe1, 0x17, 0x02, 0xd3, 0x8b, 0xd9, 0x34, 0x42, 0xd3,
	0x3d, 0xf4, 0x23, 0xd8, 0xcc, 0x6d, 0xaa, 0xc1, 0x30, 0x0e, 0x58, 0x64, 0x98, 0x67, 0x0b, 0x55,
	0xd3, 0x73, 0x96, 0x0a, 0xf9, 0x59, 0x10, 0xcf, 0xdf, 0xe8, 0xc2, 0x40, 0x5f, 0xc1, 0xde, 0x13,
	0xfe, 0x92, 0x49, 0x54, 0x69, 0xda, 0x1d, 0xc3, 0x00, 0x76, 0x52, 0x1c, 0x23, 0x9b, 0x32, 0xe4,
	0xf2, 0xb1, 0x06, 0xcc, 0xd2, 0x56, 0xcd, 0xea, 0x16, 0x05, 0xf2, 0x10, 0xd3, 0x2c, 0xca, 0x88,
	0x40, 0xc1, 0x44, 0x87, 0x40, 0x8a, 0xf0, 0x8d, 0x97, 0xf7, 0x14, 0xba, 0xa7, 0x61, 0xd8, 0x9e,
	0xeb, 0x31, 0x6c, 0xaa, 0x83, 0xc2, 0x02, 0xcb, 0x85, 0x81, 0x3e, 0x80, 0x9d, 0x3c, 0x5b, 0x23,
	0xf4, 0xe7, 0xb0, 0x37, 0xc2, 0x38, 0x79, 0x89, 0xd7, 0x85, 0x3e, 0x04, 0x52, 0x4c, 0xd8, 0x8e,
	0x80, 0xca, 0x7c, 0xad, 0x04, 0x16, 0x09, 0x1b, 0x09, 0x5c, 0xc0, 0xc1, 0x45, 0x1a, 0x70, 0xf1,
	0x1c, 0xd3, 0xa7, 0x18, 0x84, 0x6d, 0x49, 0xdc, 0x06, 0xe0, 0x78, 0xf9, 0x75, 0xa4, 0xb7, 0xcc,
	0x59, 0x70, 0xbc, 0xcc, 0x72, 0xd0, 0x13, 0x38, 0xac, 0x66, 0x6d, 0x64, 0xf2, 0x5a, 0x4d, 0x2a,
	0xce, 0x93, 0x19, 0x1f, 0xeb, 0x87, 0xd1, 0xfa, 0xfd, 0x06, 0x85, 0x4d, 0xb9, 0xae, 0x54, 0xac,
	0xff, 0x55, 0xe0, 0xf5, 0x8c, 0x2a, 0x91, 0x6a, 0xaa, 0xe3, 0xe4, 0x6f, 0x80, 0xde, 0x79, 0xf5,
	0x95, 0x9f, 0x9e, 0x3f, 0x21, 0x3f, 0xc0, 0x1b, 0xc5, 0x71, 0x47, 0xee, 0x5a, 0xc4, 0xc0, 0x32,
	0xaa, 0xbd, 0x77, 0x1a, 0xe3, 0x32, 0x4e, 0xd4, 0xfd, 0xe9, 0xcf, 0xbf, 0x5e, 0x77, 0x08, 0xdd,
	0xf6, 0x83, 0x30, 0xcc, 0x75, 0xf5, 0x43, 0xe7, 0x3e, 0x79, 0x05, 0xdb, 0xa5, 0xc1, 0x43, 0x6c,
	0x39, 0x6d, 0x83, 0xd5, 0x1b, 0x34, 0x07, 0x1a, 0xf4, 0x23, 0x8d, 0xbe, 0x4f, 0xbb, 0x3e, 0x86,
	0x4c, 0x96, 0xe0, 0x7f, 0x76, 0x60, 0xa7, 0x32, 0x6b, 0xc8, 0x3d, 0x4b, 0x62, 0xfb, 0xa4, 0xf3,
	0xee, 0xb7, 0x09, 0x35, 0x2c, 0x6e, 0x69, 0x16, 0x07, 0x74, 0xd7, 0x0f, 0x75, 0x44, 0x89, 0xc7,
	0xaf, 0x0e, 0xec, 0x5b, 0x06, 0x0c, 0x79, 0x68, 0x01, 0x58, 0x3e, 0xe6, 0xbc, 0x61, 0xdb, 0x70,
	0xc3, 0xe9, 0x8e, 0xe6, 0x74, 0x44, 0x7b, 0x7e, 0xce, 0x66, 0x9c, 0x47, 0x29, 0x5e, 0x08, 0x37,
	0x8c, 0x66, 0x91, 0x37, 0xed, 0x97, 0x5d, 0x90, 0x07, 0x8f, 0x5e, 0x15, 0x62, 0x20, 0xf7, 0x35,
	0xe4, 0x36, 0xdd, 0x50, 0xad, 0xa0, 0xd4, 0x41, 0xc1, 0xbc, 0x00, 0x58, 0x88, 0x13, 0x79, 0xcb,
	0x92, 0xa6, 0x26, 0x86, 0xde, 0xdb, 0x0d, 0x51, 0x06, 0xef, 0x50, 0xe3, 0xed, 0xd2, 0x2d, 0x3f,
	0xd5, 0xce, 0x12, 0xe4, 0x5c, 0x8e, 0x96, 0x40, 0x56, 0xe4, 0x6f, 0x09, 0x64, 0x55, 0xd3, 0x4a,
	0x90, 0xca, 0x39, 0x87, 0xfc, 0xc5, 0x81, 0xbd, 0xda, 0xa8, 0x26, 0x0f, 0x2c, 0x49, 0x97, 0x7d,
	0x32, 0x78, 0xef, 0xb6, 0x0b, 0x36, 0x44, 0x6e, 0x6b, 0x22, 0x37, 0x29, 0xf1, 0x27, 0x28, 0xcd,
	0xc6, 0x38, 0x8b, 0x51, 0x7c, 0x7e, 0x74, 0xa0, 0x5b, 0x16, 0x43, 0x62, 0x7b, 0x54, 0x56, 0x15,
	0xf6, 0xee, 0xb5, 0x88, 0x34, 0x34, 0x3c, 0x4d, 0xa3, 0x47, 0x77, 0x7c, 0x69, 0x02, 0x32, 0x75,
	0x56, 0x1c, 0x94, 0xf4, 0x14, 0x54, 0xcc, 0x2e, 0x3d, 0x75, 0xed, 0xb5, 0x4b, 0x8f, 0x45, 0x0e,
	0x8b, 0xd2, 0x53, 0x70, 0x9b, 0x0e, 0x58, 0x7c, 0x0d, 0x58, 0x3b, 0xa0, 0xf6, 0xad, 0x62, 0xed,
	0x80, 0xfa, 0x27, 0x45, 0xa1, 0x03, 0x98, 0x76, 0x9a, 0x0e, 0x78, 0xb6, 0xae, 0xff, 0x99, 0x3d,
	0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x58, 0xa3, 0x79, 0x6c, 0xed, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectManagementAPIClient is the client API for ProjectManagementAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectManagementAPIClient interface {
	AddMilestone(ctx context.Context, in *AddMilestoneRequest, opts ...grpc.CallOption) (*AddMilestoneResponse, error)
	EditMilestone(ctx context.Context, in *EditMilestoneRequest, opts ...grpc.CallOption) (*EditMilestoneResponse, error)
	DeleteMilestone(ctx context.Context, in *DeleteMilestoneRequest, opts ...grpc.CallOption) (*DeleteMilestoneResponse, error)
	MilestoneCompletion(ctx context.Context, in *MilestoneCompletionRequest, opts ...grpc.CallOption) (*MilestoneCompletionResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error)
	RejectUser(ctx context.Context, in *RejectUserRequest, opts ...grpc.CallOption) (*RejectUserResponse, error)
	GetProjectMembers(ctx context.Context, in *GetProjectMembersRequest, opts ...grpc.CallOption) (*GetProjectMembersResponse, error)
	TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error)
	Announcement(ctx context.Context, in *AnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementResponse, error)
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
}

type projectManagementAPIClient struct {
	cc *grpc.ClientConn
}

func NewProjectManagementAPIClient(cc *grpc.ClientConn) ProjectManagementAPIClient {
	return &projectManagementAPIClient{cc}
}

func (c *projectManagementAPIClient) AddMilestone(ctx context.Context, in *AddMilestoneRequest, opts ...grpc.CallOption) (*AddMilestoneResponse, error) {
	out := new(AddMilestoneResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/AddMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) EditMilestone(ctx context.Context, in *EditMilestoneRequest, opts ...grpc.CallOption) (*EditMilestoneResponse, error) {
	out := new(EditMilestoneResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/EditMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) DeleteMilestone(ctx context.Context, in *DeleteMilestoneRequest, opts ...grpc.CallOption) (*DeleteMilestoneResponse, error) {
	out := new(DeleteMilestoneResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/DeleteMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) MilestoneCompletion(ctx context.Context, in *MilestoneCompletionRequest, opts ...grpc.CallOption) (*MilestoneCompletionResponse, error) {
	out := new(MilestoneCompletionResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/MilestoneCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error) {
	out := new(RemoveUserResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/RemoveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) RejectUser(ctx context.Context, in *RejectUserRequest, opts ...grpc.CallOption) (*RejectUserResponse, error) {
	out := new(RejectUserResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/RejectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) GetProjectMembers(ctx context.Context, in *GetProjectMembersRequest, opts ...grpc.CallOption) (*GetProjectMembersResponse, error) {
	out := new(GetProjectMembersResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/GetProjectMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error) {
	out := new(TransferLeaderResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/TransferLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) Announcement(ctx context.Context, in *AnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementResponse, error) {
	out := new(AnnouncementResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/Announcement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, "/projectManagement.ProjectManagementAPI/InviteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectManagementAPIServer is the server API for ProjectManagementAPI service.
type ProjectManagementAPIServer interface {
	AddMilestone(context.Context, *AddMilestoneRequest) (*AddMilestoneResponse, error)
	EditMilestone(context.Context, *EditMilestoneRequest) (*EditMilestoneResponse, error)
	DeleteMilestone(context.Context, *DeleteMilestoneRequest) (*DeleteMilestoneResponse, error)
	MilestoneCompletion(context.Context, *MilestoneCompletionRequest) (*MilestoneCompletionResponse, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	RemoveUser(context.Context, *RemoveUserRequest) (*RemoveUserResponse, error)
	RejectUser(context.Context, *RejectUserRequest) (*RejectUserResponse, error)
	GetProjectMembers(context.Context, *GetProjectMembersRequest) (*GetProjectMembersResponse, error)
	TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error)
	Announcement(context.Context, *AnnouncementRequest) (*AnnouncementResponse, error)
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
}

func RegisterProjectManagementAPIServer(s *grpc.Server, srv ProjectManagementAPIServer) {
	s.RegisterService(&_ProjectManagementAPI_serviceDesc, srv)
}

func _ProjectManagementAPI_AddMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).AddMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/AddMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).AddMilestone(ctx, req.(*AddMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_EditMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).EditMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/EditMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).EditMilestone(ctx, req.(*EditMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_DeleteMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).DeleteMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/DeleteMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).DeleteMilestone(ctx, req.(*DeleteMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_MilestoneCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MilestoneCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).MilestoneCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/MilestoneCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).MilestoneCompletion(ctx, req.(*MilestoneCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/RemoveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).RemoveUser(ctx, req.(*RemoveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_RejectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).RejectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/RejectUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).RejectUser(ctx, req.(*RejectUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_GetProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).GetProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/GetProjectMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).GetProjectMembers(ctx, req.(*GetProjectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_TransferLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).TransferLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/TransferLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).TransferLeader(ctx, req.(*TransferLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_Announcement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).Announcement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/Announcement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).Announcement(ctx, req.(*AnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projectManagement.ProjectManagementAPI/InviteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectManagementAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "projectManagement.ProjectManagementAPI",
	HandlerType: (*ProjectManagementAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMilestone",
			Handler:    _ProjectManagementAPI_AddMilestone_Handler,
		},
		{
			MethodName: "EditMilestone",
			Handler:    _ProjectManagementAPI_EditMilestone_Handler,
		},
		{
			MethodName: "DeleteMilestone",
			Handler:    _ProjectManagementAPI_DeleteMilestone_Handler,
		},
		{
			MethodName: "MilestoneCompletion",
			Handler:    _ProjectManagementAPI_MilestoneCompletion_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _ProjectManagementAPI_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _ProjectManagementAPI_RemoveUser_Handler,
		},
		{
			MethodName: "RejectUser",
			Handler:    _ProjectManagementAPI_RejectUser_Handler,
		},
		{
			MethodName: "GetProjectMembers",
			Handler:    _ProjectManagementAPI_GetProjectMembers_Handler,
		},
		{
			MethodName: "TransferLeader",
			Handler:    _ProjectManagementAPI_TransferLeader_Handler,
		},
		{
			MethodName: "Announcement",
			Handler:    _ProjectManagementAPI_Announcement_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _ProjectManagementAPI_InviteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/project-management.proto",
}
