// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/project_management.proto

package project_management

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MilestoneModel struct {
	Milestoneid          string   `protobuf:"bytes,1,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Done                 bool     `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MilestoneModel) Reset()         { *m = MilestoneModel{} }
func (m *MilestoneModel) String() string { return proto.CompactTextString(m) }
func (*MilestoneModel) ProtoMessage()    {}
func (*MilestoneModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{0}
}

func (m *MilestoneModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MilestoneModel.Unmarshal(m, b)
}
func (m *MilestoneModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MilestoneModel.Marshal(b, m, deterministic)
}
func (m *MilestoneModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MilestoneModel.Merge(m, src)
}
func (m *MilestoneModel) XXX_Size() int {
	return xxx_messageInfo_MilestoneModel.Size(m)
}
func (m *MilestoneModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MilestoneModel.DiscardUnknown(m)
}

var xxx_messageInfo_MilestoneModel proto.InternalMessageInfo

func (m *MilestoneModel) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

func (m *MilestoneModel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MilestoneModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MilestoneModel) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *MilestoneModel) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *MilestoneModel) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type AddMilestoneRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMilestoneRequest) Reset()         { *m = AddMilestoneRequest{} }
func (m *AddMilestoneRequest) String() string { return proto.CompactTextString(m) }
func (*AddMilestoneRequest) ProtoMessage()    {}
func (*AddMilestoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{1}
}

func (m *AddMilestoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMilestoneRequest.Unmarshal(m, b)
}
func (m *AddMilestoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMilestoneRequest.Marshal(b, m, deterministic)
}
func (m *AddMilestoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMilestoneRequest.Merge(m, src)
}
func (m *AddMilestoneRequest) XXX_Size() int {
	return xxx_messageInfo_AddMilestoneRequest.Size(m)
}
func (m *AddMilestoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMilestoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMilestoneRequest proto.InternalMessageInfo

func (m *AddMilestoneRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *AddMilestoneRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddMilestoneRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddMilestoneRequest) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AddMilestoneRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type AddMilestoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMilestoneResponse) Reset()         { *m = AddMilestoneResponse{} }
func (m *AddMilestoneResponse) String() string { return proto.CompactTextString(m) }
func (*AddMilestoneResponse) ProtoMessage()    {}
func (*AddMilestoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{2}
}

func (m *AddMilestoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMilestoneResponse.Unmarshal(m, b)
}
func (m *AddMilestoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMilestoneResponse.Marshal(b, m, deterministic)
}
func (m *AddMilestoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMilestoneResponse.Merge(m, src)
}
func (m *AddMilestoneResponse) XXX_Size() int {
	return xxx_messageInfo_AddMilestoneResponse.Size(m)
}
func (m *AddMilestoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMilestoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMilestoneResponse proto.InternalMessageInfo

func (m *AddMilestoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditMilestoneRequest struct {
	Milestoneid          string   `protobuf:"bytes,1,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMilestoneRequest) Reset()         { *m = EditMilestoneRequest{} }
func (m *EditMilestoneRequest) String() string { return proto.CompactTextString(m) }
func (*EditMilestoneRequest) ProtoMessage()    {}
func (*EditMilestoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{3}
}

func (m *EditMilestoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMilestoneRequest.Unmarshal(m, b)
}
func (m *EditMilestoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMilestoneRequest.Marshal(b, m, deterministic)
}
func (m *EditMilestoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMilestoneRequest.Merge(m, src)
}
func (m *EditMilestoneRequest) XXX_Size() int {
	return xxx_messageInfo_EditMilestoneRequest.Size(m)
}
func (m *EditMilestoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMilestoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditMilestoneRequest proto.InternalMessageInfo

func (m *EditMilestoneRequest) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

func (m *EditMilestoneRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditMilestoneRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditMilestoneRequest) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *EditMilestoneRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type EditMilestoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMilestoneResponse) Reset()         { *m = EditMilestoneResponse{} }
func (m *EditMilestoneResponse) String() string { return proto.CompactTextString(m) }
func (*EditMilestoneResponse) ProtoMessage()    {}
func (*EditMilestoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{4}
}

func (m *EditMilestoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMilestoneResponse.Unmarshal(m, b)
}
func (m *EditMilestoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMilestoneResponse.Marshal(b, m, deterministic)
}
func (m *EditMilestoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMilestoneResponse.Merge(m, src)
}
func (m *EditMilestoneResponse) XXX_Size() int {
	return xxx_messageInfo_EditMilestoneResponse.Size(m)
}
func (m *EditMilestoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMilestoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditMilestoneResponse proto.InternalMessageInfo

func (m *EditMilestoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteMilestoneRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Milestoneid          string   `protobuf:"bytes,2,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMilestoneRequest) Reset()         { *m = DeleteMilestoneRequest{} }
func (m *DeleteMilestoneRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMilestoneRequest) ProtoMessage()    {}
func (*DeleteMilestoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{5}
}

func (m *DeleteMilestoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMilestoneRequest.Unmarshal(m, b)
}
func (m *DeleteMilestoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMilestoneRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMilestoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMilestoneRequest.Merge(m, src)
}
func (m *DeleteMilestoneRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMilestoneRequest.Size(m)
}
func (m *DeleteMilestoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMilestoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMilestoneRequest proto.InternalMessageInfo

func (m *DeleteMilestoneRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *DeleteMilestoneRequest) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

type DeleteMilestoneResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMilestoneResponse) Reset()         { *m = DeleteMilestoneResponse{} }
func (m *DeleteMilestoneResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMilestoneResponse) ProtoMessage()    {}
func (*DeleteMilestoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{6}
}

func (m *DeleteMilestoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMilestoneResponse.Unmarshal(m, b)
}
func (m *DeleteMilestoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMilestoneResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMilestoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMilestoneResponse.Merge(m, src)
}
func (m *DeleteMilestoneResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMilestoneResponse.Size(m)
}
func (m *DeleteMilestoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMilestoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMilestoneResponse proto.InternalMessageInfo

func (m *DeleteMilestoneResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type MilestoneCompletionRequest struct {
	Milestoneid          string   `protobuf:"bytes,2,opt,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MilestoneCompletionRequest) Reset()         { *m = MilestoneCompletionRequest{} }
func (m *MilestoneCompletionRequest) String() string { return proto.CompactTextString(m) }
func (*MilestoneCompletionRequest) ProtoMessage()    {}
func (*MilestoneCompletionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{7}
}

func (m *MilestoneCompletionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MilestoneCompletionRequest.Unmarshal(m, b)
}
func (m *MilestoneCompletionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MilestoneCompletionRequest.Marshal(b, m, deterministic)
}
func (m *MilestoneCompletionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MilestoneCompletionRequest.Merge(m, src)
}
func (m *MilestoneCompletionRequest) XXX_Size() int {
	return xxx_messageInfo_MilestoneCompletionRequest.Size(m)
}
func (m *MilestoneCompletionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MilestoneCompletionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MilestoneCompletionRequest proto.InternalMessageInfo

func (m *MilestoneCompletionRequest) GetMilestoneid() string {
	if m != nil {
		return m.Milestoneid
	}
	return ""
}

type MilestoneCompletionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MilestoneCompletionResponse) Reset()         { *m = MilestoneCompletionResponse{} }
func (m *MilestoneCompletionResponse) String() string { return proto.CompactTextString(m) }
func (*MilestoneCompletionResponse) ProtoMessage()    {}
func (*MilestoneCompletionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{8}
}

func (m *MilestoneCompletionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MilestoneCompletionResponse.Unmarshal(m, b)
}
func (m *MilestoneCompletionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MilestoneCompletionResponse.Marshal(b, m, deterministic)
}
func (m *MilestoneCompletionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MilestoneCompletionResponse.Merge(m, src)
}
func (m *MilestoneCompletionResponse) XXX_Size() int {
	return xxx_messageInfo_MilestoneCompletionResponse.Size(m)
}
func (m *MilestoneCompletionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MilestoneCompletionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MilestoneCompletionResponse proto.InternalMessageInfo

func (m *MilestoneCompletionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetAllMilestonesRequest struct {
	Milestoneid          []string `protobuf:"bytes,1,rep,name=milestoneid,proto3" json:"milestoneid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllMilestonesRequest) Reset()         { *m = GetAllMilestonesRequest{} }
func (m *GetAllMilestonesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllMilestonesRequest) ProtoMessage()    {}
func (*GetAllMilestonesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{9}
}

func (m *GetAllMilestonesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMilestonesRequest.Unmarshal(m, b)
}
func (m *GetAllMilestonesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMilestonesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllMilestonesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMilestonesRequest.Merge(m, src)
}
func (m *GetAllMilestonesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllMilestonesRequest.Size(m)
}
func (m *GetAllMilestonesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMilestonesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMilestonesRequest proto.InternalMessageInfo

func (m *GetAllMilestonesRequest) GetMilestoneid() []string {
	if m != nil {
		return m.Milestoneid
	}
	return nil
}

type GetAllMilestonesResponse struct {
	Success              bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Milestones           []*MilestoneModel `protobuf:"bytes,2,rep,name=milestones,proto3" json:"milestones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAllMilestonesResponse) Reset()         { *m = GetAllMilestonesResponse{} }
func (m *GetAllMilestonesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllMilestonesResponse) ProtoMessage()    {}
func (*GetAllMilestonesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{10}
}

func (m *GetAllMilestonesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMilestonesResponse.Unmarshal(m, b)
}
func (m *GetAllMilestonesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMilestonesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllMilestonesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMilestonesResponse.Merge(m, src)
}
func (m *GetAllMilestonesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllMilestonesResponse.Size(m)
}
func (m *GetAllMilestonesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMilestonesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMilestonesResponse proto.InternalMessageInfo

func (m *GetAllMilestonesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetAllMilestonesResponse) GetMilestones() []*MilestoneModel {
	if m != nil {
		return m.Milestones
	}
	return nil
}

type GetProjectMembersRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Memberslist          []string `protobuf:"bytes,2,rep,name=memberslist,proto3" json:"memberslist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectMembersRequest) Reset()         { *m = GetProjectMembersRequest{} }
func (m *GetProjectMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectMembersRequest) ProtoMessage()    {}
func (*GetProjectMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{11}
}

func (m *GetProjectMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectMembersRequest.Unmarshal(m, b)
}
func (m *GetProjectMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectMembersRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectMembersRequest.Merge(m, src)
}
func (m *GetProjectMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectMembersRequest.Size(m)
}
func (m *GetProjectMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectMembersRequest proto.InternalMessageInfo

func (m *GetProjectMembersRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *GetProjectMembersRequest) GetMemberslist() []string {
	if m != nil {
		return m.Memberslist
	}
	return nil
}

type GetProjectMembersResponse struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Users                []*UserTuple `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetProjectMembersResponse) Reset()         { *m = GetProjectMembersResponse{} }
func (m *GetProjectMembersResponse) String() string { return proto.CompactTextString(m) }
func (*GetProjectMembersResponse) ProtoMessage()    {}
func (*GetProjectMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{12}
}

func (m *GetProjectMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectMembersResponse.Unmarshal(m, b)
}
func (m *GetProjectMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectMembersResponse.Marshal(b, m, deterministic)
}
func (m *GetProjectMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectMembersResponse.Merge(m, src)
}
func (m *GetProjectMembersResponse) XXX_Size() int {
	return xxx_messageInfo_GetProjectMembersResponse.Size(m)
}
func (m *GetProjectMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectMembersResponse proto.InternalMessageInfo

func (m *GetProjectMembersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetProjectMembersResponse) GetUsers() []*UserTuple {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserTuple struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTuple) Reset()         { *m = UserTuple{} }
func (m *UserTuple) String() string { return proto.CompactTextString(m) }
func (*UserTuple) ProtoMessage()    {}
func (*UserTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{13}
}

func (m *UserTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTuple.Unmarshal(m, b)
}
func (m *UserTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTuple.Marshal(b, m, deterministic)
}
func (m *UserTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTuple.Merge(m, src)
}
func (m *UserTuple) XXX_Size() int {
	return xxx_messageInfo_UserTuple.Size(m)
}
func (m *UserTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTuple.DiscardUnknown(m)
}

var xxx_messageInfo_UserTuple proto.InternalMessageInfo

func (m *UserTuple) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserTuple) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

type InviteUserRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Recipientemail       string   `protobuf:"bytes,2,opt,name=recipientemail,proto3" json:"recipientemail,omitempty"`
	Senderemail          string   `protobuf:"bytes,3,opt,name=senderemail,proto3" json:"senderemail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserRequest) Reset()         { *m = InviteUserRequest{} }
func (m *InviteUserRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUserRequest) ProtoMessage()    {}
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{14}
}

func (m *InviteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserRequest.Unmarshal(m, b)
}
func (m *InviteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserRequest.Marshal(b, m, deterministic)
}
func (m *InviteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserRequest.Merge(m, src)
}
func (m *InviteUserRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUserRequest.Size(m)
}
func (m *InviteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserRequest proto.InternalMessageInfo

func (m *InviteUserRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *InviteUserRequest) GetRecipientemail() string {
	if m != nil {
		return m.Recipientemail
	}
	return ""
}

func (m *InviteUserRequest) GetSenderemail() string {
	if m != nil {
		return m.Senderemail
	}
	return ""
}

type InviteUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserResponse) Reset()         { *m = InviteUserResponse{} }
func (m *InviteUserResponse) String() string { return proto.CompactTextString(m) }
func (*InviteUserResponse) ProtoMessage()    {}
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{15}
}

func (m *InviteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserResponse.Unmarshal(m, b)
}
func (m *InviteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserResponse.Marshal(b, m, deterministic)
}
func (m *InviteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserResponse.Merge(m, src)
}
func (m *InviteUserResponse) XXX_Size() int {
	return xxx_messageInfo_InviteUserResponse.Size(m)
}
func (m *InviteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserResponse proto.InternalMessageInfo

func (m *InviteUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AcceptInviteRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Xid                  string   `protobuf:"bytes,2,opt,name=xid,proto3" json:"xid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptInviteRequest) Reset()         { *m = AcceptInviteRequest{} }
func (m *AcceptInviteRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptInviteRequest) ProtoMessage()    {}
func (*AcceptInviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{16}
}

func (m *AcceptInviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptInviteRequest.Unmarshal(m, b)
}
func (m *AcceptInviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptInviteRequest.Marshal(b, m, deterministic)
}
func (m *AcceptInviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptInviteRequest.Merge(m, src)
}
func (m *AcceptInviteRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptInviteRequest.Size(m)
}
func (m *AcceptInviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptInviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptInviteRequest proto.InternalMessageInfo

func (m *AcceptInviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AcceptInviteRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

type AcceptInviteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptInviteResponse) Reset()         { *m = AcceptInviteResponse{} }
func (m *AcceptInviteResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptInviteResponse) ProtoMessage()    {}
func (*AcceptInviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{17}
}

func (m *AcceptInviteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptInviteResponse.Unmarshal(m, b)
}
func (m *AcceptInviteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptInviteResponse.Marshal(b, m, deterministic)
}
func (m *AcceptInviteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptInviteResponse.Merge(m, src)
}
func (m *AcceptInviteResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptInviteResponse.Size(m)
}
func (m *AcceptInviteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptInviteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptInviteResponse proto.InternalMessageInfo

func (m *AcceptInviteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RejectInviteRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Xid                  string   `protobuf:"bytes,2,opt,name=xid,proto3" json:"xid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectInviteRequest) Reset()         { *m = RejectInviteRequest{} }
func (m *RejectInviteRequest) String() string { return proto.CompactTextString(m) }
func (*RejectInviteRequest) ProtoMessage()    {}
func (*RejectInviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{18}
}

func (m *RejectInviteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectInviteRequest.Unmarshal(m, b)
}
func (m *RejectInviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectInviteRequest.Marshal(b, m, deterministic)
}
func (m *RejectInviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectInviteRequest.Merge(m, src)
}
func (m *RejectInviteRequest) XXX_Size() int {
	return xxx_messageInfo_RejectInviteRequest.Size(m)
}
func (m *RejectInviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectInviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectInviteRequest proto.InternalMessageInfo

func (m *RejectInviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RejectInviteRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

type RejectInviteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectInviteResponse) Reset()         { *m = RejectInviteResponse{} }
func (m *RejectInviteResponse) String() string { return proto.CompactTextString(m) }
func (*RejectInviteResponse) ProtoMessage()    {}
func (*RejectInviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{19}
}

func (m *RejectInviteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectInviteResponse.Unmarshal(m, b)
}
func (m *RejectInviteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectInviteResponse.Marshal(b, m, deterministic)
}
func (m *RejectInviteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectInviteResponse.Merge(m, src)
}
func (m *RejectInviteResponse) XXX_Size() int {
	return xxx_messageInfo_RejectInviteResponse.Size(m)
}
func (m *RejectInviteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectInviteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectInviteResponse proto.InternalMessageInfo

func (m *RejectInviteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddUserRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{20}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{21}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveUserRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserRequest) Reset()         { *m = RemoveUserRequest{} }
func (m *RemoveUserRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveUserRequest) ProtoMessage()    {}
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{22}
}

func (m *RemoveUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserRequest.Unmarshal(m, b)
}
func (m *RemoveUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserRequest.Marshal(b, m, deterministic)
}
func (m *RemoveUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserRequest.Merge(m, src)
}
func (m *RemoveUserRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveUserRequest.Size(m)
}
func (m *RemoveUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserRequest proto.InternalMessageInfo

func (m *RemoveUserRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *RemoveUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RemoveUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserResponse) Reset()         { *m = RemoveUserResponse{} }
func (m *RemoveUserResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveUserResponse) ProtoMessage()    {}
func (*RemoveUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{23}
}

func (m *RemoveUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserResponse.Unmarshal(m, b)
}
func (m *RemoveUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserResponse.Marshal(b, m, deterministic)
}
func (m *RemoveUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserResponse.Merge(m, src)
}
func (m *RemoveUserResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveUserResponse.Size(m)
}
func (m *RemoveUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserResponse proto.InternalMessageInfo

func (m *RemoveUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RejectUserRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectUserRequest) Reset()         { *m = RejectUserRequest{} }
func (m *RejectUserRequest) String() string { return proto.CompactTextString(m) }
func (*RejectUserRequest) ProtoMessage()    {}
func (*RejectUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{24}
}

func (m *RejectUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectUserRequest.Unmarshal(m, b)
}
func (m *RejectUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectUserRequest.Marshal(b, m, deterministic)
}
func (m *RejectUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectUserRequest.Merge(m, src)
}
func (m *RejectUserRequest) XXX_Size() int {
	return xxx_messageInfo_RejectUserRequest.Size(m)
}
func (m *RejectUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectUserRequest proto.InternalMessageInfo

func (m *RejectUserRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *RejectUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RejectUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectUserResponse) Reset()         { *m = RejectUserResponse{} }
func (m *RejectUserResponse) String() string { return proto.CompactTextString(m) }
func (*RejectUserResponse) ProtoMessage()    {}
func (*RejectUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{25}
}

func (m *RejectUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectUserResponse.Unmarshal(m, b)
}
func (m *RejectUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectUserResponse.Marshal(b, m, deterministic)
}
func (m *RejectUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectUserResponse.Merge(m, src)
}
func (m *RejectUserResponse) XXX_Size() int {
	return xxx_messageInfo_RejectUserResponse.Size(m)
}
func (m *RejectUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectUserResponse proto.InternalMessageInfo

func (m *RejectUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type TransferLeaderRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Newleader            string   `protobuf:"bytes,2,opt,name=newleader,proto3" json:"newleader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferLeaderRequest) Reset()         { *m = TransferLeaderRequest{} }
func (m *TransferLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*TransferLeaderRequest) ProtoMessage()    {}
func (*TransferLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{26}
}

func (m *TransferLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferLeaderRequest.Unmarshal(m, b)
}
func (m *TransferLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferLeaderRequest.Marshal(b, m, deterministic)
}
func (m *TransferLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferLeaderRequest.Merge(m, src)
}
func (m *TransferLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_TransferLeaderRequest.Size(m)
}
func (m *TransferLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferLeaderRequest proto.InternalMessageInfo

func (m *TransferLeaderRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *TransferLeaderRequest) GetNewleader() string {
	if m != nil {
		return m.Newleader
	}
	return ""
}

type TransferLeaderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferLeaderResponse) Reset()         { *m = TransferLeaderResponse{} }
func (m *TransferLeaderResponse) String() string { return proto.CompactTextString(m) }
func (*TransferLeaderResponse) ProtoMessage()    {}
func (*TransferLeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{27}
}

func (m *TransferLeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferLeaderResponse.Unmarshal(m, b)
}
func (m *TransferLeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferLeaderResponse.Marshal(b, m, deterministic)
}
func (m *TransferLeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferLeaderResponse.Merge(m, src)
}
func (m *TransferLeaderResponse) XXX_Size() int {
	return xxx_messageInfo_TransferLeaderResponse.Size(m)
}
func (m *TransferLeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferLeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferLeaderResponse proto.InternalMessageInfo

func (m *TransferLeaderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AnnouncementRequest struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Poster               string   `protobuf:"bytes,2,opt,name=poster,proto3" json:"poster,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Pin                  bool     `protobuf:"varint,4,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementRequest) Reset()         { *m = AnnouncementRequest{} }
func (m *AnnouncementRequest) String() string { return proto.CompactTextString(m) }
func (*AnnouncementRequest) ProtoMessage()    {}
func (*AnnouncementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{28}
}

func (m *AnnouncementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementRequest.Unmarshal(m, b)
}
func (m *AnnouncementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementRequest.Marshal(b, m, deterministic)
}
func (m *AnnouncementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementRequest.Merge(m, src)
}
func (m *AnnouncementRequest) XXX_Size() int {
	return xxx_messageInfo_AnnouncementRequest.Size(m)
}
func (m *AnnouncementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementRequest proto.InternalMessageInfo

func (m *AnnouncementRequest) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *AnnouncementRequest) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *AnnouncementRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AnnouncementRequest) GetPin() bool {
	if m != nil {
		return m.Pin
	}
	return false
}

type AnnouncementResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementResponse) Reset()         { *m = AnnouncementResponse{} }
func (m *AnnouncementResponse) String() string { return proto.CompactTextString(m) }
func (*AnnouncementResponse) ProtoMessage()    {}
func (*AnnouncementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{29}
}

func (m *AnnouncementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementResponse.Unmarshal(m, b)
}
func (m *AnnouncementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementResponse.Marshal(b, m, deterministic)
}
func (m *AnnouncementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementResponse.Merge(m, src)
}
func (m *AnnouncementResponse) XXX_Size() int {
	return xxx_messageInfo_AnnouncementResponse.Size(m)
}
func (m *AnnouncementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementResponse proto.InternalMessageInfo

func (m *AnnouncementResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveNotificationRequest struct {
	Notification         string   `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNotificationRequest) Reset()         { *m = RemoveNotificationRequest{} }
func (m *RemoveNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveNotificationRequest) ProtoMessage()    {}
func (*RemoveNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{30}
}

func (m *RemoveNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNotificationRequest.Unmarshal(m, b)
}
func (m *RemoveNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNotificationRequest.Marshal(b, m, deterministic)
}
func (m *RemoveNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNotificationRequest.Merge(m, src)
}
func (m *RemoveNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveNotificationRequest.Size(m)
}
func (m *RemoveNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNotificationRequest proto.InternalMessageInfo

func (m *RemoveNotificationRequest) GetNotification() string {
	if m != nil {
		return m.Notification
	}
	return ""
}

func (m *RemoveNotificationRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type RemoveNotificationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveNotificationResponse) Reset()         { *m = RemoveNotificationResponse{} }
func (m *RemoveNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveNotificationResponse) ProtoMessage()    {}
func (*RemoveNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4ae41adcddedd9d, []int{31}
}

func (m *RemoveNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveNotificationResponse.Unmarshal(m, b)
}
func (m *RemoveNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveNotificationResponse.Marshal(b, m, deterministic)
}
func (m *RemoveNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveNotificationResponse.Merge(m, src)
}
func (m *RemoveNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveNotificationResponse.Size(m)
}
func (m *RemoveNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveNotificationResponse proto.InternalMessageInfo

func (m *RemoveNotificationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*MilestoneModel)(nil), "MilestoneModel")
	proto.RegisterType((*AddMilestoneRequest)(nil), "AddMilestoneRequest")
	proto.RegisterType((*AddMilestoneResponse)(nil), "AddMilestoneResponse")
	proto.RegisterType((*EditMilestoneRequest)(nil), "EditMilestoneRequest")
	proto.RegisterType((*EditMilestoneResponse)(nil), "EditMilestoneResponse")
	proto.RegisterType((*DeleteMilestoneRequest)(nil), "DeleteMilestoneRequest")
	proto.RegisterType((*DeleteMilestoneResponse)(nil), "DeleteMilestoneResponse")
	proto.RegisterType((*MilestoneCompletionRequest)(nil), "MilestoneCompletionRequest")
	proto.RegisterType((*MilestoneCompletionResponse)(nil), "MilestoneCompletionResponse")
	proto.RegisterType((*GetAllMilestonesRequest)(nil), "GetAllMilestonesRequest")
	proto.RegisterType((*GetAllMilestonesResponse)(nil), "GetAllMilestonesResponse")
	proto.RegisterType((*GetProjectMembersRequest)(nil), "GetProjectMembersRequest")
	proto.RegisterType((*GetProjectMembersResponse)(nil), "GetProjectMembersResponse")
	proto.RegisterType((*UserTuple)(nil), "UserTuple")
	proto.RegisterType((*InviteUserRequest)(nil), "InviteUserRequest")
	proto.RegisterType((*InviteUserResponse)(nil), "InviteUserResponse")
	proto.RegisterType((*AcceptInviteRequest)(nil), "AcceptInviteRequest")
	proto.RegisterType((*AcceptInviteResponse)(nil), "AcceptInviteResponse")
	proto.RegisterType((*RejectInviteRequest)(nil), "RejectInviteRequest")
	proto.RegisterType((*RejectInviteResponse)(nil), "RejectInviteResponse")
	proto.RegisterType((*AddUserRequest)(nil), "AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "AddUserResponse")
	proto.RegisterType((*RemoveUserRequest)(nil), "RemoveUserRequest")
	proto.RegisterType((*RemoveUserResponse)(nil), "RemoveUserResponse")
	proto.RegisterType((*RejectUserRequest)(nil), "RejectUserRequest")
	proto.RegisterType((*RejectUserResponse)(nil), "RejectUserResponse")
	proto.RegisterType((*TransferLeaderRequest)(nil), "TransferLeaderRequest")
	proto.RegisterType((*TransferLeaderResponse)(nil), "TransferLeaderResponse")
	proto.RegisterType((*AnnouncementRequest)(nil), "AnnouncementRequest")
	proto.RegisterType((*AnnouncementResponse)(nil), "AnnouncementResponse")
	proto.RegisterType((*RemoveNotificationRequest)(nil), "RemoveNotificationRequest")
	proto.RegisterType((*RemoveNotificationResponse)(nil), "RemoveNotificationResponse")
}

func init() { proto.RegisterFile("protos/project_management.proto", fileDescriptor_b4ae41adcddedd9d) }

var fileDescriptor_b4ae41adcddedd9d = []byte{
	// 1098 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4b, 0x6f, 0x1c, 0x45,
	0x10, 0xd6, 0xae, 0x1f, 0xb1, 0xcb, 0xb1, 0xbd, 0xee, 0x7d, 0x78, 0x3c, 0x36, 0x64, 0xd5, 0x07,
	0x64, 0x05, 0xa9, 0x07, 0x1c, 0x09, 0x50, 0x10, 0xa0, 0x15, 0xa0, 0x28, 0x52, 0x1c, 0x45, 0x4b,
	0x22, 0xc4, 0x21, 0x42, 0x93, 0x9d, 0xf2, 0xd2, 0x30, 0xaf, 0x4c, 0xf7, 0x26, 0x9c, 0xe1, 0xcc,
	0x89, 0x3b, 0xbf, 0x80, 0x7f, 0xc3, 0x5f, 0xe0, 0x87, 0xa0, 0xee, 0x79, 0x6c, 0xcf, 0xcb, 0x63,
	0xf9, 0x80, 0x72, 0x9b, 0xae, 0xee, 0xfa, 0xbe, 0xea, 0x47, 0x7d, 0x55, 0x03, 0xf7, 0xe2, 0x24,
	0x92, 0x91, 0x70, 0xe2, 0x24, 0xfa, 0x19, 0x17, 0xf2, 0xc7, 0xc0, 0x0d, 0xdd, 0x25, 0x06, 0x18,
	0x4a, 0xa6, 0x67, 0xec, 0xb3, 0x65, 0x14, 0x2d, 0x7d, 0x74, 0xdc, 0x98, 0x3b, 0x6e, 0x18, 0x46,
	0xd2, 0x95, 0x3c, 0x0a, 0x45, 0x3a, 0x4b, 0xff, 0xee, 0xc1, 0xc1, 0x25, 0xf7, 0x51, 0xc8, 0x28,
	0xc4, 0xcb, 0xc8, 0x43, 0x9f, 0x4c, 0x61, 0x2f, 0xc8, 0x2d, 0xdc, 0xb3, 0x7a, 0xd3, 0xde, 0xf9,
	0xee, 0xdc, 0x34, 0x91, 0x11, 0x6c, 0x49, 0x2e, 0x7d, 0xb4, 0xfa, 0x7a, 0x2e, 0x1d, 0x28, 0x3f,
	0x0f, 0xc5, 0x22, 0xe1, 0xb1, 0x22, 0xb0, 0x36, 0x52, 0x3f, 0xc3, 0xa4, 0xfc, 0x56, 0x02, 0x13,
	0x61, 0x6d, 0x4e, 0x37, 0x94, 0x9f, 0x1e, 0x90, 0x09, 0x6c, 0xbf, 0x45, 0xbe, 0xfc, 0x49, 0x5a,
	0x5b, 0xd3, 0xde, 0xf9, 0xd6, 0x3c, 0x1b, 0x11, 0x02, 0x9b, 0x5e, 0x14, 0xa2, 0xb5, 0x3d, 0xed,
	0x9d, 0xef, 0xcc, 0xf5, 0x37, 0xfd, 0xa3, 0x07, 0xc3, 0x99, 0xe7, 0x15, 0x11, 0xcf, 0xf1, 0xf5,
	0x0a, 0x85, 0x24, 0x03, 0xd8, 0xf8, 0xb5, 0x88, 0x55, 0x7d, 0xfe, 0x3f, 0x31, 0xd2, 0x8f, 0x60,
	0x54, 0x0e, 0x47, 0xc4, 0x51, 0x28, 0x90, 0x58, 0x70, 0x47, 0xac, 0x16, 0x0b, 0x14, 0x42, 0xc7,
	0xb4, 0x33, 0xcf, 0x87, 0xf4, 0xaf, 0x1e, 0x8c, 0xbe, 0xf5, 0xb8, 0xac, 0x6d, 0xe1, 0x1d, 0x39,
	0x76, 0xfa, 0x31, 0x8c, 0x2b, 0xf1, 0x75, 0xee, 0xe9, 0x09, 0x4c, 0xbe, 0x41, 0x1f, 0x25, 0xde,
	0xe0, 0x5e, 0x2a, 0xdb, 0xec, 0xd7, 0xb6, 0x49, 0x1f, 0xc0, 0x71, 0x0d, 0xad, 0x33, 0x84, 0x2f,
	0xc1, 0x2e, 0x96, 0x7f, 0x1d, 0x05, 0xb1, 0x8f, 0x6a, 0xeb, 0x2d, 0x67, 0xdb, 0x40, 0xfa, 0x29,
	0x9c, 0x36, 0xfa, 0x77, 0x12, 0x7f, 0x0e, 0xc7, 0x8f, 0x50, 0xce, 0x7c, 0xbf, 0x70, 0x17, 0xad,
	0x37, 0xba, 0x51, 0x65, 0x45, 0xb0, 0xea, 0xce, 0x5d, 0x94, 0xc4, 0x01, 0x28, 0x40, 0x84, 0xd5,
	0x9f, 0x6e, 0x9c, 0xef, 0x5d, 0x1c, 0xb2, 0x72, 0x16, 0xcf, 0x8d, 0x25, 0xf4, 0xa9, 0xa6, 0x79,
	0x96, 0x2a, 0xc4, 0x25, 0x06, 0xaf, 0x30, 0x11, 0xd7, 0xdf, 0x50, 0xba, 0xc6, 0xe7, 0x42, 0x6a,
	0x7c, 0x15, 0xf6, 0xda, 0x44, 0xbf, 0x87, 0x93, 0x06, 0xbc, 0xce, 0xb8, 0xa7, 0xf9, 0x3b, 0x4c,
	0x43, 0x06, 0xf6, 0x42, 0x60, 0xf2, 0x7c, 0x15, 0xfb, 0x98, 0xbd, 0x49, 0xfa, 0x15, 0xec, 0x16,
	0x36, 0xf5, 0x6c, 0x31, 0x70, 0xb9, 0x9f, 0xc5, 0x96, 0x0e, 0xc8, 0x19, 0xec, 0x5e, 0xf1, 0x44,
	0xc8, 0xd0, 0x0d, 0xf2, 0x44, 0x58, 0x1b, 0x68, 0x04, 0x47, 0x8f, 0xc3, 0x37, 0x5c, 0xa2, 0x82,
	0x69, 0xdf, 0xe2, 0x07, 0x70, 0x90, 0xe0, 0x82, 0xc7, 0x1c, 0x43, 0x99, 0x72, 0xa4, 0x48, 0x15,
	0xab, 0x3a, 0x0a, 0x81, 0xa1, 0x87, 0x49, 0xba, 0x28, 0xcb, 0x2d, 0xc3, 0x44, 0x19, 0x10, 0x93,
	0xb0, 0xf3, 0xb9, 0x7c, 0x01, 0xc3, 0xd9, 0x62, 0x81, 0xb1, 0x4c, 0xbd, 0xf2, 0x10, 0x9b, 0xf7,
	0x9a, 0x05, 0xde, 0x2f, 0x02, 0xd7, 0x7a, 0x53, 0x72, 0xbf, 0x09, 0xe1, 0x1c, 0xd5, 0x3d, 0xdd,
	0x9a, 0xb0, 0xec, 0xde, 0x49, 0xf8, 0x19, 0x1c, 0xcc, 0x3c, 0xef, 0xfa, 0xf3, 0x2f, 0xd8, 0xfb,
	0x06, 0x3b, 0xfd, 0x10, 0x0e, 0x0b, 0xcf, 0x1b, 0xe4, 0xdd, 0xd1, 0x1c, 0x83, 0xe8, 0x0d, 0xde,
	0x86, 0x89, 0x01, 0x31, 0x9d, 0x6f, 0x46, 0xa6, 0x4e, 0xe1, 0xd6, 0x64, 0x6b, 0xe7, 0x4e, 0xb2,
	0x47, 0x30, 0x7e, 0x9e, 0xb8, 0xa1, 0xb8, 0xc2, 0xe4, 0x09, 0xba, 0xde, 0x75, 0x84, 0x67, 0xb0,
	0x1b, 0xe2, 0x5b, 0x5f, 0xaf, 0xca, 0x93, 0xa1, 0x30, 0xd0, 0x0b, 0x98, 0x54, 0x81, 0x3a, 0xc9,
	0x7f, 0x81, 0xe1, 0x2c, 0x0c, 0xa3, 0x55, 0xb8, 0xd0, 0x3d, 0x44, 0x3b, 0xf5, 0x04, 0xb6, 0xe3,
	0x48, 0xc8, 0x82, 0x37, 0x1b, 0x29, 0xe8, 0x00, 0x85, 0x70, 0x97, 0x98, 0xa5, 0x4b, 0x3e, 0x54,
	0x18, 0x31, 0x0f, 0xad, 0x4d, 0x4d, 0xa8, 0x3e, 0xf5, 0x6b, 0x2e, 0x91, 0x75, 0x86, 0xf7, 0x1d,
	0x9c, 0xa4, 0x17, 0xf7, 0x34, 0x92, 0xfc, 0x8a, 0x2f, 0x5c, 0x53, 0xe5, 0x29, 0xdc, 0x0d, 0x0d,
	0x73, 0x16, 0x6d, 0xc9, 0xa6, 0x9a, 0x0a, 0x25, 0x35, 0x59, 0xd0, 0xfa, 0x9b, 0x7e, 0x02, 0x76,
	0x13, 0x68, 0x57, 0x30, 0x17, 0xbf, 0xef, 0xc1, 0x28, 0x17, 0xc1, 0xa2, 0xeb, 0x9a, 0x3d, 0x7b,
	0x4c, 0x5e, 0xc0, 0x5d, 0xb3, 0x2b, 0x20, 0x23, 0xd6, 0xd0, 0xb3, 0xd8, 0x63, 0xd6, 0xd4, 0x3a,
	0x50, 0xeb, 0xb7, 0x7f, 0xfe, 0xfd, 0xb3, 0x4f, 0xe8, 0xbe, 0xe3, 0x7a, 0x5e, 0x21, 0xe2, 0x0f,
	0x7b, 0xf7, 0xc9, 0x0f, 0xb0, 0x5f, 0xaa, 0xcc, 0x64, 0xcc, 0x9a, 0x3a, 0x09, 0x7b, 0xc2, 0x1a,
	0x0b, 0x38, 0x3d, 0xd1, 0xc8, 0x43, 0x7a, 0xe0, 0xa0, 0xc7, 0x65, 0x09, 0xda, 0x85, 0xc3, 0x4a,
	0xcd, 0x25, 0xc7, 0xac, 0xb9, 0xa6, 0xdb, 0x16, 0x6b, 0x29, 0xcf, 0xf4, 0x54, 0x13, 0x8c, 0xe9,
	0xc0, 0xf1, 0xf4, 0x8a, 0x12, 0xc5, 0x6b, 0x18, 0x36, 0x54, 0x58, 0x72, 0xca, 0xda, 0xeb, 0xb6,
	0x7d, 0xc6, 0xae, 0x29, 0xca, 0xf4, 0x9e, 0xa6, 0x3b, 0xa1, 0x23, 0xa7, 0x20, 0x5a, 0x14, 0xab,
	0x14, 0x25, 0xc2, 0xa0, 0x5a, 0x5e, 0x89, 0xc5, 0x5a, 0xca, 0xb5, 0x7d, 0xc2, 0xda, 0x6a, 0x31,
	0x3d, 0xd3, 0x4c, 0x13, 0x7a, 0xe4, 0x2c, 0x51, 0xba, 0xbe, 0xbf, 0xae, 0xad, 0x8a, 0x66, 0x06,
	0x77, 0x32, 0xdd, 0x22, 0x87, 0xac, 0xac, 0x7d, 0xf6, 0x80, 0x55, 0x24, 0x8d, 0x0e, 0x35, 0xd6,
	0x3e, 0xdd, 0x51, 0xf7, 0xab, 0xde, 0x9f, 0x82, 0xb8, 0x04, 0x58, 0x0b, 0x12, 0x21, 0xac, 0x26,
	0x6d, 0xf6, 0x90, 0xd5, 0x15, 0x8b, 0x4e, 0x34, 0xd6, 0x80, 0xee, 0x39, 0x89, 0x9e, 0x2c, 0xc1,
	0xe5, 0x92, 0xa3, 0xe1, 0x2a, 0xe2, 0xa5, 0xe1, 0xaa, 0x9a, 0x54, 0x82, 0x53, 0x93, 0x39, 0x1c,
	0x87, 0xa3, 0x5a, 0xbd, 0x27, 0xfa, 0xb8, 0x1a, 0x7b, 0x0a, 0xdb, 0x66, 0xad, 0xed, 0x01, 0x7d,
	0x4f, 0x73, 0x1c, 0x53, 0xa2, 0x8e, 0x32, 0xfb, 0x69, 0xc9, 0x7a, 0x0b, 0x45, 0xf5, 0x12, 0x0e,
	0xca, 0x9a, 0x45, 0x26, 0xac, 0x51, 0x0d, 0xed, 0x63, 0xd6, 0x2c, 0x6e, 0xd4, 0xd6, 0x0c, 0x23,
	0x7a, 0xe8, 0xc8, 0x6c, 0x41, 0xaa, 0x87, 0x0a, 0x5e, 0x65, 0xa6, 0xa1, 0x38, 0x2a, 0x33, 0xeb,
	0x6a, 0xa7, 0x32, 0xb3, 0x41, 0x96, 0xcc, 0xcc, 0x34, 0xa6, 0xb3, 0xf3, 0x5e, 0x77, 0x01, 0x84,
	0xb0, 0x5a, 0x0f, 0x62, 0x0f, 0x59, 0xbd, 0x4d, 0x30, 0xce, 0x9b, 0xeb, 0xc9, 0xfc, 0xbc, 0x5f,
	0xc2, 0xc0, 0xa8, 0xf2, 0xa9, 0x70, 0x8d, 0x58, 0x43, 0xdf, 0xa0, 0x22, 0x6d, 0x68, 0x07, 0x8c,
	0xf7, 0xea, 0xea, 0x69, 0x5e, 0xe0, 0x64, 0xf0, 0x46, 0x4d, 0xcf, 0xe1, 0x1b, 0xba, 0x04, 0x7b,
	0xcc, 0x9a, 0x8a, 0xbf, 0x01, 0x9f, 0xbe, 0x93, 0x32, 0x7c, 0x90, 0x17, 0x57, 0x53, 0x4e, 0x89,
	0xcd, 0x5a, 0x85, 0xdb, 0x3e, 0x65, 0xed, 0xfa, 0x4b, 0xdf, 0xd7, 0x64, 0x16, 0x1d, 0x66, 0x6f,
	0xdc, 0x94, 0xf3, 0x87, 0xbd, 0xfb, 0xaf, 0xb6, 0xf5, 0x8f, 0xec, 0x83, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x2a, 0x22, 0xd2, 0x36, 0x09, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectManagementAPIClient is the client API for ProjectManagementAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectManagementAPIClient interface {
	AddMilestone(ctx context.Context, in *AddMilestoneRequest, opts ...grpc.CallOption) (*AddMilestoneResponse, error)
	EditMilestone(ctx context.Context, in *EditMilestoneRequest, opts ...grpc.CallOption) (*EditMilestoneResponse, error)
	DeleteMilestone(ctx context.Context, in *DeleteMilestoneRequest, opts ...grpc.CallOption) (*DeleteMilestoneResponse, error)
	MilestoneCompletion(ctx context.Context, in *MilestoneCompletionRequest, opts ...grpc.CallOption) (*MilestoneCompletionResponse, error)
	GetAllMilestones(ctx context.Context, in *GetAllMilestonesRequest, opts ...grpc.CallOption) (*GetAllMilestonesResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error)
	RejectUser(ctx context.Context, in *RejectUserRequest, opts ...grpc.CallOption) (*RejectUserResponse, error)
	GetProjectMembers(ctx context.Context, in *GetProjectMembersRequest, opts ...grpc.CallOption) (*GetProjectMembersResponse, error)
	TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error)
	Announcement(ctx context.Context, in *AnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementResponse, error)
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
	AcceptInvitation(ctx context.Context, in *AcceptInviteRequest, opts ...grpc.CallOption) (*AcceptInviteResponse, error)
	RejectInvitation(ctx context.Context, in *RejectInviteRequest, opts ...grpc.CallOption) (*RejectInviteResponse, error)
	RemoveNotification(ctx context.Context, in *RemoveNotificationRequest, opts ...grpc.CallOption) (*RemoveNotificationResponse, error)
}

type projectManagementAPIClient struct {
	cc *grpc.ClientConn
}

func NewProjectManagementAPIClient(cc *grpc.ClientConn) ProjectManagementAPIClient {
	return &projectManagementAPIClient{cc}
}

func (c *projectManagementAPIClient) AddMilestone(ctx context.Context, in *AddMilestoneRequest, opts ...grpc.CallOption) (*AddMilestoneResponse, error) {
	out := new(AddMilestoneResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/AddMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) EditMilestone(ctx context.Context, in *EditMilestoneRequest, opts ...grpc.CallOption) (*EditMilestoneResponse, error) {
	out := new(EditMilestoneResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/EditMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) DeleteMilestone(ctx context.Context, in *DeleteMilestoneRequest, opts ...grpc.CallOption) (*DeleteMilestoneResponse, error) {
	out := new(DeleteMilestoneResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/DeleteMilestone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) MilestoneCompletion(ctx context.Context, in *MilestoneCompletionRequest, opts ...grpc.CallOption) (*MilestoneCompletionResponse, error) {
	out := new(MilestoneCompletionResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/MilestoneCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) GetAllMilestones(ctx context.Context, in *GetAllMilestonesRequest, opts ...grpc.CallOption) (*GetAllMilestonesResponse, error) {
	out := new(GetAllMilestonesResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/GetAllMilestones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*RemoveUserResponse, error) {
	out := new(RemoveUserResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/RemoveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) RejectUser(ctx context.Context, in *RejectUserRequest, opts ...grpc.CallOption) (*RejectUserResponse, error) {
	out := new(RejectUserResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/RejectUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) GetProjectMembers(ctx context.Context, in *GetProjectMembersRequest, opts ...grpc.CallOption) (*GetProjectMembersResponse, error) {
	out := new(GetProjectMembersResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/GetProjectMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) TransferLeader(ctx context.Context, in *TransferLeaderRequest, opts ...grpc.CallOption) (*TransferLeaderResponse, error) {
	out := new(TransferLeaderResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/TransferLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) Announcement(ctx context.Context, in *AnnouncementRequest, opts ...grpc.CallOption) (*AnnouncementResponse, error) {
	out := new(AnnouncementResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/Announcement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/InviteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) AcceptInvitation(ctx context.Context, in *AcceptInviteRequest, opts ...grpc.CallOption) (*AcceptInviteResponse, error) {
	out := new(AcceptInviteResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/AcceptInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) RejectInvitation(ctx context.Context, in *RejectInviteRequest, opts ...grpc.CallOption) (*RejectInviteResponse, error) {
	out := new(RejectInviteResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/RejectInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectManagementAPIClient) RemoveNotification(ctx context.Context, in *RemoveNotificationRequest, opts ...grpc.CallOption) (*RemoveNotificationResponse, error) {
	out := new(RemoveNotificationResponse)
	err := c.cc.Invoke(ctx, "/ProjectManagementAPI/RemoveNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectManagementAPIServer is the server API for ProjectManagementAPI service.
type ProjectManagementAPIServer interface {
	AddMilestone(context.Context, *AddMilestoneRequest) (*AddMilestoneResponse, error)
	EditMilestone(context.Context, *EditMilestoneRequest) (*EditMilestoneResponse, error)
	DeleteMilestone(context.Context, *DeleteMilestoneRequest) (*DeleteMilestoneResponse, error)
	MilestoneCompletion(context.Context, *MilestoneCompletionRequest) (*MilestoneCompletionResponse, error)
	GetAllMilestones(context.Context, *GetAllMilestonesRequest) (*GetAllMilestonesResponse, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	RemoveUser(context.Context, *RemoveUserRequest) (*RemoveUserResponse, error)
	RejectUser(context.Context, *RejectUserRequest) (*RejectUserResponse, error)
	GetProjectMembers(context.Context, *GetProjectMembersRequest) (*GetProjectMembersResponse, error)
	TransferLeader(context.Context, *TransferLeaderRequest) (*TransferLeaderResponse, error)
	Announcement(context.Context, *AnnouncementRequest) (*AnnouncementResponse, error)
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
	AcceptInvitation(context.Context, *AcceptInviteRequest) (*AcceptInviteResponse, error)
	RejectInvitation(context.Context, *RejectInviteRequest) (*RejectInviteResponse, error)
	RemoveNotification(context.Context, *RemoveNotificationRequest) (*RemoveNotificationResponse, error)
}

func RegisterProjectManagementAPIServer(s *grpc.Server, srv ProjectManagementAPIServer) {
	s.RegisterService(&_ProjectManagementAPI_serviceDesc, srv)
}

func _ProjectManagementAPI_AddMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).AddMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/AddMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).AddMilestone(ctx, req.(*AddMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_EditMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).EditMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/EditMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).EditMilestone(ctx, req.(*EditMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_DeleteMilestone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMilestoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).DeleteMilestone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/DeleteMilestone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).DeleteMilestone(ctx, req.(*DeleteMilestoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_MilestoneCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MilestoneCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).MilestoneCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/MilestoneCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).MilestoneCompletion(ctx, req.(*MilestoneCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_GetAllMilestones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMilestonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).GetAllMilestones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/GetAllMilestones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).GetAllMilestones(ctx, req.(*GetAllMilestonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/RemoveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).RemoveUser(ctx, req.(*RemoveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_RejectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).RejectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/RejectUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).RejectUser(ctx, req.(*RejectUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_GetProjectMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).GetProjectMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/GetProjectMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).GetProjectMembers(ctx, req.(*GetProjectMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_TransferLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).TransferLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/TransferLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).TransferLeader(ctx, req.(*TransferLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_Announcement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).Announcement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/Announcement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).Announcement(ctx, req.(*AnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/InviteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/AcceptInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).AcceptInvitation(ctx, req.(*AcceptInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_RejectInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).RejectInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/RejectInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).RejectInvitation(ctx, req.(*RejectInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectManagementAPI_RemoveNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectManagementAPIServer).RemoveNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProjectManagementAPI/RemoveNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectManagementAPIServer).RemoveNotification(ctx, req.(*RemoveNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectManagementAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProjectManagementAPI",
	HandlerType: (*ProjectManagementAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMilestone",
			Handler:    _ProjectManagementAPI_AddMilestone_Handler,
		},
		{
			MethodName: "EditMilestone",
			Handler:    _ProjectManagementAPI_EditMilestone_Handler,
		},
		{
			MethodName: "DeleteMilestone",
			Handler:    _ProjectManagementAPI_DeleteMilestone_Handler,
		},
		{
			MethodName: "MilestoneCompletion",
			Handler:    _ProjectManagementAPI_MilestoneCompletion_Handler,
		},
		{
			MethodName: "GetAllMilestones",
			Handler:    _ProjectManagementAPI_GetAllMilestones_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _ProjectManagementAPI_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _ProjectManagementAPI_RemoveUser_Handler,
		},
		{
			MethodName: "RejectUser",
			Handler:    _ProjectManagementAPI_RejectUser_Handler,
		},
		{
			MethodName: "GetProjectMembers",
			Handler:    _ProjectManagementAPI_GetProjectMembers_Handler,
		},
		{
			MethodName: "TransferLeader",
			Handler:    _ProjectManagementAPI_TransferLeader_Handler,
		},
		{
			MethodName: "Announcement",
			Handler:    _ProjectManagementAPI_Announcement_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _ProjectManagementAPI_InviteUser_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _ProjectManagementAPI_AcceptInvitation_Handler,
		},
		{
			MethodName: "RejectInvitation",
			Handler:    _ProjectManagementAPI_RejectInvitation_Handler,
		},
		{
			MethodName: "RemoveNotification",
			Handler:    _ProjectManagementAPI_RemoveNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/project_management.proto",
}
